apiVersion: apps/v1
kind: Deployment
metadata:
  name: revmerito-ai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: revmerito-ai
  template:
    metadata:
      labels:
        app: revmerito-ai
    spec:
      containers:
      - name: revmerito-ai
        image: your-dockerhub-username/revmerito-sales-ai:latest
        ports:
        - containerPort: 8501
        env:
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: api-secrets
              key: openai
        - name: AZURE_SPEECH_KEY
          valueFrom:
            secretKeyRef:
              name: api-secrets
              key: azure
        - name: DEEPGRAM_API_KEY
          valueFrom:
            secretKeyRef:
              name: api-secrets
              key: deepgram
