apiVersion: v1
kind: Service
metadata:
  name: revmerito-service
spec:
  type: LoadBalancer
  selector:
    app: revmerito-ai
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8501
